orbs:
  cxflow: checkmarx-ts/cxflow@1.0.5
version: 2.1
workflows:
  sast-scan:
    jobs:
      - cxflow/scan:
          ast-apiUrl: 'http://cx-ast-testing.dev.checkmarx-ts.com'
          ast-incremental: false
          ast-preset: Checkmarx Default
          ast-webAppUrl: 'http://cx-ast-testing.dev.checkmarx-ts.com'
          cxgo-base-url: 'https://api.checkmarx.net'
          cxgo-configuration: Default Configuration
          cxgo-multi-tenant: true
          cxgo-portal-url: 'https://cloud.checkmarx.net'
          cxgo-scan-preset: '1,2,3,4,5,9'
          filters:
            branches:
              only:
                - master
          preset: Checkmarx Express
          project: CxProject
          report-file: vulns.json
          sca-accessControlUrl: 'https://platform.checkmarx.net'
          sca-apiUrl: 'https://api.scacheckmarx.com'
          sca-appUrl: 'https://sca.scacheckmarx.com'
          scanners: 'sca,ast,cxgo,sast'
          team: \CxServer\SP\Checkmarx
  version: 2

